# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NotiServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotiServiceExtension
  pod 'CocoaAsyncSocket'
end

target 'sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample

end
